//
//desde el directorio "grpc", ejecutar el comando:
//protoc --go_out=plugins=grpc:data_name data_name/data_name.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: data_name/data_name.proto

package data_name

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderResCode int32

const (
	OrderResCode_No  OrderResCode = 0
	OrderResCode_Yes OrderResCode = 1
)

// Enum value maps for OrderResCode.
var (
	OrderResCode_name = map[int32]string{
		0: "No",
		1: "Yes",
	}
	OrderResCode_value = map[string]int32{
		"No":  0,
		"Yes": 1,
	}
)

func (x OrderResCode) Enum() *OrderResCode {
	p := new(OrderResCode)
	*p = x
	return p
}

func (x OrderResCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderResCode) Descriptor() protoreflect.EnumDescriptor {
	return file_data_name_data_name_proto_enumTypes[0].Descriptor()
}

func (OrderResCode) Type() protoreflect.EnumType {
	return &file_data_name_data_name_proto_enumTypes[0]
}

func (x OrderResCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderResCode.Descriptor instead.
func (OrderResCode) EnumDescriptor() ([]byte, []int) {
	return file_data_name_data_name_proto_rawDescGZIP(), []int{0}
}

type OrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Req:
	//	*OrderReq_FileName
	//	*OrderReq_ChunkId
	Req isOrderReq_Req `protobuf_oneof:"Req"`
}

func (x *OrderReq) Reset() {
	*x = OrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_name_data_name_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReq) ProtoMessage() {}

func (x *OrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_data_name_data_name_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReq.ProtoReflect.Descriptor instead.
func (*OrderReq) Descriptor() ([]byte, []int) {
	return file_data_name_data_name_proto_rawDescGZIP(), []int{0}
}

func (m *OrderReq) GetReq() isOrderReq_Req {
	if m != nil {
		return m.Req
	}
	return nil
}

func (x *OrderReq) GetFileName() string {
	if x, ok := x.GetReq().(*OrderReq_FileName); ok {
		return x.FileName
	}
	return ""
}

func (x *OrderReq) GetChunkId() int64 {
	if x, ok := x.GetReq().(*OrderReq_ChunkId); ok {
		return x.ChunkId
	}
	return 0
}

type isOrderReq_Req interface {
	isOrderReq_Req()
}

type OrderReq_FileName struct {
	FileName string `protobuf:"bytes,1,opt,name=FileName,proto3,oneof"`
}

type OrderReq_ChunkId struct {
	ChunkId int64 `protobuf:"varint,2,opt,name=ChunkId,proto3,oneof"`
}

func (*OrderReq_FileName) isOrderReq_Req() {}

func (*OrderReq_ChunkId) isOrderReq_Req() {}

type OrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId  int64 `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	ChunkId int64 `protobuf:"varint,2,opt,name=ChunkId,proto3" json:"ChunkId,omitempty"`
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_name_data_name_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_name_data_name_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_data_name_data_name_proto_rawDescGZIP(), []int{1}
}

func (x *OrderInfo) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *OrderInfo) GetChunkId() int64 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

type OrderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResCode OrderResCode `protobuf:"varint,1,opt,name=ResCode,proto3,enum=data_name.OrderResCode" json:"ResCode,omitempty"`
}

func (x *OrderRes) Reset() {
	*x = OrderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_name_data_name_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRes) ProtoMessage() {}

func (x *OrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_data_name_data_name_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRes.ProtoReflect.Descriptor instead.
func (*OrderRes) Descriptor() ([]byte, []int) {
	return file_data_name_data_name_proto_rawDescGZIP(), []int{2}
}

func (x *OrderRes) GetResCode() OrderResCode {
	if x != nil {
		return x.ResCode
	}
	return OrderResCode_No
}

var File_data_name_data_name_proto protoreflect.FileDescriptor

var file_data_name_data_name_proto_rawDesc = []byte{
	0x0a, 0x19, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4b, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x1c, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x42, 0x05, 0x0a, 0x03,
	0x52, 0x65, 0x71, 0x22, 0x3d, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x49, 0x64, 0x22, 0x3d, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x31,
	0x0a, 0x07, 0x52, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x52, 0x65, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x2a, 0x1f, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x06, 0x0a, 0x02, 0x4e, 0x6f, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x59, 0x65, 0x73,
	0x10, 0x01, 0x32, 0x85, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x3c, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x12, 0x3b, 0x0a,
	0x0b, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_data_name_data_name_proto_rawDescOnce sync.Once
	file_data_name_data_name_proto_rawDescData = file_data_name_data_name_proto_rawDesc
)

func file_data_name_data_name_proto_rawDescGZIP() []byte {
	file_data_name_data_name_proto_rawDescOnce.Do(func() {
		file_data_name_data_name_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_name_data_name_proto_rawDescData)
	})
	return file_data_name_data_name_proto_rawDescData
}

var file_data_name_data_name_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_name_data_name_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_name_data_name_proto_goTypes = []interface{}{
	(OrderResCode)(0), // 0: data_name.OrderResCode
	(*OrderReq)(nil),  // 1: data_name.OrderReq
	(*OrderInfo)(nil), // 2: data_name.OrderInfo
	(*OrderRes)(nil),  // 3: data_name.OrderRes
}
var file_data_name_data_name_proto_depIdxs = []int32{
	0, // 0: data_name.OrderRes.ResCode:type_name -> data_name.OrderResCode
	1, // 1: data_name.DataName.RequestOrder:input_type -> data_name.OrderReq
	1, // 2: data_name.DataName.InformOrder:input_type -> data_name.OrderReq
	3, // 3: data_name.DataName.RequestOrder:output_type -> data_name.OrderRes
	3, // 4: data_name.DataName.InformOrder:output_type -> data_name.OrderRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_name_data_name_proto_init() }
func file_data_name_data_name_proto_init() {
	if File_data_name_data_name_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_name_data_name_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_name_data_name_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_name_data_name_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_data_name_data_name_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*OrderReq_FileName)(nil),
		(*OrderReq_ChunkId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_name_data_name_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_name_data_name_proto_goTypes,
		DependencyIndexes: file_data_name_data_name_proto_depIdxs,
		EnumInfos:         file_data_name_data_name_proto_enumTypes,
		MessageInfos:      file_data_name_data_name_proto_msgTypes,
	}.Build()
	File_data_name_data_name_proto = out.File
	file_data_name_data_name_proto_rawDesc = nil
	file_data_name_data_name_proto_goTypes = nil
	file_data_name_data_name_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataNameClient is the client API for DataName service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataNameClient interface {
	//NO IMPLEMENTADO AÚN
	//este se usa solo en caso de que el algoritmo sea de exclusion centralizada:
	RequestOrder(ctx context.Context, opts ...grpc.CallOption) (DataName_RequestOrderClient, error)
	//NO IMPLEMENTADO AÚN
	//datanode informa al namenode cual es el orden que tiene que escribir en el log
	InformOrder(ctx context.Context, opts ...grpc.CallOption) (DataName_InformOrderClient, error)
}

type dataNameClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNameClient(cc grpc.ClientConnInterface) DataNameClient {
	return &dataNameClient{cc}
}

func (c *dataNameClient) RequestOrder(ctx context.Context, opts ...grpc.CallOption) (DataName_RequestOrderClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataName_serviceDesc.Streams[0], "/data_name.DataName/RequestOrder", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataNameRequestOrderClient{stream}
	return x, nil
}

type DataName_RequestOrderClient interface {
	Send(*OrderReq) error
	CloseAndRecv() (*OrderRes, error)
	grpc.ClientStream
}

type dataNameRequestOrderClient struct {
	grpc.ClientStream
}

func (x *dataNameRequestOrderClient) Send(m *OrderReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataNameRequestOrderClient) CloseAndRecv() (*OrderRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(OrderRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataNameClient) InformOrder(ctx context.Context, opts ...grpc.CallOption) (DataName_InformOrderClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataName_serviceDesc.Streams[1], "/data_name.DataName/InformOrder", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataNameInformOrderClient{stream}
	return x, nil
}

type DataName_InformOrderClient interface {
	Send(*OrderReq) error
	CloseAndRecv() (*OrderRes, error)
	grpc.ClientStream
}

type dataNameInformOrderClient struct {
	grpc.ClientStream
}

func (x *dataNameInformOrderClient) Send(m *OrderReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataNameInformOrderClient) CloseAndRecv() (*OrderRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(OrderRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataNameServer is the server API for DataName service.
type DataNameServer interface {
	//NO IMPLEMENTADO AÚN
	//este se usa solo en caso de que el algoritmo sea de exclusion centralizada:
	RequestOrder(DataName_RequestOrderServer) error
	//NO IMPLEMENTADO AÚN
	//datanode informa al namenode cual es el orden que tiene que escribir en el log
	InformOrder(DataName_InformOrderServer) error
}

// UnimplementedDataNameServer can be embedded to have forward compatible implementations.
type UnimplementedDataNameServer struct {
}

func (*UnimplementedDataNameServer) RequestOrder(DataName_RequestOrderServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestOrder not implemented")
}
func (*UnimplementedDataNameServer) InformOrder(DataName_InformOrderServer) error {
	return status.Errorf(codes.Unimplemented, "method InformOrder not implemented")
}

func RegisterDataNameServer(s *grpc.Server, srv DataNameServer) {
	s.RegisterService(&_DataName_serviceDesc, srv)
}

func _DataName_RequestOrder_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataNameServer).RequestOrder(&dataNameRequestOrderServer{stream})
}

type DataName_RequestOrderServer interface {
	SendAndClose(*OrderRes) error
	Recv() (*OrderReq, error)
	grpc.ServerStream
}

type dataNameRequestOrderServer struct {
	grpc.ServerStream
}

func (x *dataNameRequestOrderServer) SendAndClose(m *OrderRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataNameRequestOrderServer) Recv() (*OrderReq, error) {
	m := new(OrderReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DataName_InformOrder_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataNameServer).InformOrder(&dataNameInformOrderServer{stream})
}

type DataName_InformOrderServer interface {
	SendAndClose(*OrderRes) error
	Recv() (*OrderReq, error)
	grpc.ServerStream
}

type dataNameInformOrderServer struct {
	grpc.ServerStream
}

func (x *dataNameInformOrderServer) SendAndClose(m *OrderRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataNameInformOrderServer) Recv() (*OrderReq, error) {
	m := new(OrderReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DataName_serviceDesc = grpc.ServiceDesc{
	ServiceName: "data_name.DataName",
	HandlerType: (*DataNameServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestOrder",
			Handler:       _DataName_RequestOrder_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "InformOrder",
			Handler:       _DataName_InformOrder_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "data_name/data_name.proto",
}
